### ISSUE TITLE
Ignore verbose STDERR output

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-test-ci-environments#23]
After upgrading to Electron v5 see a lot more in the STDERR when `DISPLAY` variable is set incorrectly. It does not affect `STDOUT` or user messaging

normal user warning

```
root@aa0a8a4d6bad:~/app# DISPLAY=555 DEBUG= npx cypress verify
[15:27:30]  Verifying Cypress can run /root/.cache/Cypress/3.5.0/Cypress [started]
⚠ Warning: Cypress failed to start.

This is likely due to a misconfigured DISPLAY environment variable.

DISPLAY was set to: "555"

Cypress will attempt to fix the problem and rerun.

[15:27:31]  Verifying Cypress can run /root/.cache/Cypress/3.5.0/Cypress [completed]
```

`STDERR` if we print it

```
ypress:cli smoke test command: /root/.cache/Cypress/3.5.0/Cypress/Cypress --no-sandbox --smoke-test --ping=250 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: { Error: Command failed: /root/.cache/Cypress/3.5.0/Cypress/Cypress --no-sandbox --smoke-test --ping=250
/root/.cache/Cypress/3.5.0/Cypress/Cypress: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/Cypress/3.5.0/Cypress/Cypress)
/root/.cache/Cypress/3.5.0/Cypress/Cypress: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/Cypress/3.5.0/Cypress/Cypress)
[1718:0930/152644.340243:WARNING:browser_main_loop.cc(281)] Gtk: cannot open display: 555


    at makeError (/root/app/node_modules/cypress/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/root/app/node_modules/cypress/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  stdout: '',
  stderr: '/root/.cache/Cypress/3.5.0/Cypress/Cypress: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/Cypress/3.5.0/Cypress/Cypress)\n/root/.cache/Cypress/3.5.0/Cypress/Cypress: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/Cypress/3.5.0/Cypress/Cypress)\n[1718:0930/152644.340243:WARNING:browser_main_loop.cc(281)] Gtk: cannot open display: 555\n',
  failed: true,
  signal: null,
  cmd: '/root/.cache/Cypress/3.5.0/Cypress/Cypress --no-sandbox --smoke-test --ping=250',
  timedOut: false,
  killed: false } +55ms
  cypress:cli error message: /root/.cache/Cypress/3.5.0/Cypress/Cypress: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/Cypress/3.5.0/Cypress/Cypress)
/root/.cache/Cypress/3.5.0/Cypress/Cypress: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /root/.cache/Cypress/3.5.0/Cypress/Cypress)
[1718:0930/152644.340243:WARNING:browser_main_loop.cc(281)] Gtk: cannot open display: 555
```

**Comment by bahmutov** [comment]
Example failed CI build https://circleci.com/gh/cypress-io/cypress-test-ci-environments/7040
